---
- name: setup local
  hosts: localhost
  remote_user: root
  tasks:
  - name: install dependencies
    package:
      name: sudo
      state: present

  - name: create sudoers.d
    file:
      path: /etc/sudoers.d
      state: directory

  - name: wheel group passwordless sudo
    copy:
      content: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
      dest: /etc/sudoers.d/wheel
      validate: "/usr/sbin/visudo -csf %s"

  - name: cut SSH as root
    lineinfile:
      path: /etc/ssh/sshd_config 
      regexp: '^PermitRootLogin yes$'
      line: 'PermitRootLogin no'
    notify:
      - restart_sshd

  handlers:
  - name: restart_sshd
    systemd:
      name: sshd
      state: restarted
