---
- hosts: new
  remote_user: root
  any_errors_fatal: true
  gather_facts: false
  vars:
    target_src: "main.go"
  tasks:
  - shell: gofmt -w main.go && go build -ldflags "-s -w" main.go
    delegate_to: localhost
  
  - name: copy executable
    copy:
      src: ./main
      dest:  /opt/sysinfo
    notify: restart sysinfo service

  - name: copy config 
    copy:
      src: ./config.ini
      dest:  /opt/config.ini
    notify: restart sysinfo service

  handlers:
  - name: restart sysinfo service
    systemd:
      name: sysinfo
      state: restarted
    
