---
- hosts: new
  remote_user: root
  any_errors_fatal: true
  gather_facts: false
  tasks:
  - shell: gofmt -w main.go && go build -ldflags "-s -w" main.go
    delegate_to: localhost

  - name: copy api file
    copy:
      src: ./main
      dest:  /opt/sysinfo
    notify: restart sysinfo service

  - name: copy api config file
    copy:
      src: ./config.ini
      dest:  /opt/config.ini
    notify: restart sysinfo service

  handlers:
  - name: restart sysinfo service
    systemd:
      name: sysinfo
      state: restarted
    
